### ISSUE TITLE
modeOfIssuance conversion is sometimes wrong

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1243]
**Describe the bug**
This document in `ilspilot` has the wrong mode of issuance: https://ilspilot.test.rero.ch/professional/records/documents/detail/782990
According to conversion specifications, it should be: rdami:1002 / set

**To Reproduce**
Example: https://ilspilot.test.rero.ch/professional/records/documents/detail/782990

**Expected behavior**
According to conversion specifications, it should be: rdami:1002 / set

**Context**
* server: ilspilot.test.rero.ch
* version: v0.12.0

Impact: The link from the [child document](https://ilspilot.test.rero.ch/professional/records/documents/detail/783145) is labelled "Revue" instead of "Series" >
![image](https://user-images.githubusercontent.com/8154915/94149118-c7827380-fe77-11ea-86c5-a69881169964.png)

**Comment by reropag** [comment]
It is not a conversion problem. The problem is related to an error in the incoming record data used to build the pilot database.
The record has been corrected into Virtua since. So this issue can be closed.

**Comment by pronguen** [comment]
@BadrAly This issue has been considered for ilspilot (3rd version)? Because the problem is still present...

**Comment by pronguen** [comment]
This problem seems to be unsolved in https://ilspilot.test.rero.ch (v 0.14.1).

The series "Folio" (MARC 035 $a 0337698) has a mode of issuance *rdami:1003 / periodical*. According to spec, it should be *rdami:1003 / MonographicSeries*. In Virtua, the data is set as for MonographicSeries.

We should check if this was corrected for the deployment of https://ilspilot.test.rero.ch (v 0.14.1) or after.

**Comment by iGormilhit** [comment]
@pronguen As discussed with @BadrAly this issue is related with incompatibilites between serials holdings that cannot be attached to monographic document, a situation that exists in Virtual. We need to understand how to resolve this situation in RERO ILS.

For now, in order to be able to import Virtua data into RERO ILS, the document type is intentionally changed before importing.

**Comment by pronguen** [comment]
This issue is solved. Concerning the holdings according to document types, see #1612.
