### ISSUE TITLE
Notifications for patrons without e-mail: country not translated

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2452]
**Describe the bug**

The country is not translated in the notification to the staff for patron without e-mail.
Note: If the adress is Switzerland, the country field doesn't appear in the letter.

**To Reproduce**

Ex with the 'availability' notification.
1. Change the adress of a user. Ex Katie >> Belgium.
2. Add a request for Katie.
3. Validate the request.

**Expected behavior**

The country should be translated.

**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v1.5.1` or the commit hash (see frontpage).
* browser: [if relevant, e.g. chrome, safari, version 78].

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/12396034/136974758-ec0e3851-0aeb-4808-b0b2-08b5c9feb536.png)

**Additional context**

**Comment by zannkukai** [comment]
@ManaDeweerdt It should be solved. Could you rested and confirm ? If solved, could you close this issue

**Comment by ManaDeweerdt** [comment]
I've tested on ils.test (1.7.0) and the country (ex Belgium) is still not translated.

**Comment by PascalRepond** [comment]
Seems to be fixed
